remote_theme: jitinnair1/gradfolio
plugins:
    - jekyll-remote-theme

title: PineTS
description: Pine Script in TypeScript - Write trading indicators with TypeScript
show_downloads: true
google_analytics:
github:
    repository_url: https://github.com/alaa-eddine/PineTS
